spring:
  redis:
    host: 127.0.0.1
    port: 6379
    password: 123456
    database: 12
    lettuce:
      pool:
        max-active: 300
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/wk_module?characterEncoding=utf8&useSSL=false&zeroDateTimeBehavior=convertToNull&tinyInt1isBit=false&serverTimezone=Asia/Shanghai&useAffectedRows=true&allowPublicKeyRetrieval=true
    username: root
    password: password
  elasticsearch:
    uris: 192.168.1.126:9200
    username:
    password:
  jackson:
    dateFormat: yyyy-MM-dd HH:mm:ss
    timeZone: GMT+8
rocketmq:
  accessKey: accessKey
  secretKey: secretKey
  nameSrvAddr: 127.0.0.1:9876
  topicOne: message
  topicTwo: topB
  groupId: GID_WK_MODULES
wukong:
  ids:
    auth:
      appId:
      clientId: 94a7808f-4d61-45ce-9ae1-de507b4d4bd2
      clientSecret: b5d5415f-534d-4037-a7c6-f6a0d4cb39a5
      requestUri: http://127.0.0.1:88/open/oauth2/token
      redirectUri: http://127.0.0.1:44311/open/oauth2/token
  common:
    upload:
      type: local
      region: D:/wukong
      domain: commonFile/download